# source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

target 'qjdkdtApp' do

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  # Pods for qjdkdtApp
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  
  pod 'IQKeyboardManager', ‘~> 6.5.6’
  pod 'AFNetworking', ‘~> 4.0.1’
  pod 'Masonry', ‘~> 1.1.0’
  pod 'MJExtension', ‘~> 3.2.2’
  pod 'UMCCommon', ‘~> 7.2.2’
  pod 'UMCCommonLog', ‘~> 2.0.0’
  pod 'UMCSecurityPlugins', ‘~> 1.0.6’
  pod 'UMCPush', ‘~> 3.3.1’
#  pod 'UMCShare/Social/WeChat'
  pod 'WechatOpenSDK', ‘~> 1.8.7.1’
  pod 'MBProgressHUD+JDragon', ‘~> 0.0.3’

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
  

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

